### ISSUE TITLE
Syntax error in test_single_img.py

### ISSUE THREAD

**Issue by 4knahs** [greatlog/DAN#12]
```
Traceback (most recent call last):
  File "test_single_img.py", line 15, in <module>
    import options as option
  File "/home/SERILOCAL/mario.a/DAN/codes/config/DAN/options.py", line 10, in <module>
    from utils import OrderedYaml
  File "../../utils/__init__.py", line 1, in <module>
    from .deg_utils import *
  File "../../utils/deg_utils.py", line 88
    mask_iso = np.random.uniform(0, 1, (batch)) < rate_iso]
                                                          ^
SyntaxError: invalid syntax
```

**Comment by 4knahs** [comment]
Also 
`import utils.util as util
` should be 
`import utils as util`

**Comment by greatlog** [comment]
Yes, you are right. It seems that I have mixed the codes of different versions. I will try to fix it as soon as possible.
