### ISSUE TITLE
关于您给的model进行fine-tuning的问题

### ISSUE THREAD

**Issue by xuboming8** [greatlog/DAN#25]
你好，我使用你给出的训练好的model进行test没有问题，但我加载它进行fine-tuning的时候，会出现如下问题，请问是为什么？
Traceback (most recent call last):
  File "train.py", line 337, in <module>
    main()
  File "train.py", line 202, in main
    model = create_model(opt)  # load pretrained model of SFTMD
  File "/media/xbm/data/xbm/Self-ImageSR-Extend/DAN-master/codes/config/DANv1/models/__init__.py", line 17, in create_model
    m = M(opt)
  File "/media/xbm/data/xbm/Self-ImageSR-Extend/DAN-master/codes/config/DANv1/models/blind_model.py", line 37, in __init__
    self.load()
  File "/media/xbm/data/xbm/Self-ImageSR-Extend/DAN-master/codes/config/DANv1/models/blind_model.py", line 234, in load
    self.load_network(load_path_G, self.netG, self.opt["path"]["strict_load"])
  File "/media/xbm/data/xbm/Self-ImageSR-Extend/DAN-master/codes/config/DANv1/models/base_model.py", line 102, in load_network
    network.load_state_dict(load_net_clean, strict=strict)
  File "/home/xbm/anaconda3/envs/pytorch1.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DAN:
        Missing key(s) in state_dict: "init_kernel", "init_ker_map".

**Comment by greatlog** [comment]
请问是使用的最新版的代码嘛。现在的版本应该不会出现这样的问题。

**Comment by xuboming8** [comment]
你好 我是7月5日下载您的代码。另外fine-tuing x4的时候，训练出来的图像有一定几率变成全黑，请问你遇到过这样的情况吗

**Comment by xuboming8** [comment]
你好 我是7月5日下载您的代码。另外fine-tuning x4的时候，训练出来的图像有一定几率变成全黑，请问你遇到过这样的情况吗

**Comment by greatlog** [comment]
关于 fine tune报错的问题，可是吧yml文件中strict load设置成false试试 。
关于图像一定几率变黑，是因为训练发散了，此时loss很大，需要从最近的一个正常的training state接着训练，可以参考[Issue#8](https://github.com/greatlog/DAN/issues/8)
