### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by koreadhkim** [greatlog/DAN#9]
Traceback (most recent call last):
  File "test_single_img.py", line 36, in <module>
    model = create_model(opt)
  File "/workspace/Visual_Media_Restore/DAN/codes/config/DAN/models/__init__.py", line 17, in create_model
    m = M(opt)
  File "/workspace/Visual_Media_Restore/DAN/codes/config/DAN/models/blind_model.py", line 27, in __init__
    self.netG = networks.define_G(opt).to(self.device)
  File "/workspace/Visual_Media_Restore/DAN/codes/config/DAN/models/networks.py", line 43, in define_G
    pca_matrix_path=opt["pca_matrix_path"],
  File "/workspace/Visual_Media_Restore/DAN/codes/config/DAN/models/modules/dan_arch.py", line 173, in __init__
    self.init_kernel.view(1, 1, self.ksize ** 2).matmul(self.encoder)[:, 0],
RuntimeError: Expected tensor to have size 441 at dimension 1, but got size 121 for argument #2 'batch2' (while checking arguments for bmm)

**Comment by greatlog** [comment]
It seems that the test setting and checkpoints are not compatible. I have changed the default setting. It may work well now.
